---
  # general
  samples: "samples.tsv"
  output_dir: "results"
  logs: "logs"
  local_log: "logs/local_log"
  cluster_log: "logs/cluster_log"
  scripts: "../scripts"

  # annotation
  gtf: "/tungstenfs/groups/gbioinfo/DB/WormBase/WS270/c_elegans.PRJNA13758.WS270.canonical_geneset.gtf"
  genome: "/tungstenfs/groups/gbioinfo/DB/WormBase/WS270/c_elegans.PRJNA13758.WS270.genomic.fa"
  bowtie_index: "/tungstenfs/groups/gbioinfo/DB/WormBase/WS270/indexes/STAR_index_sjdb_100_bowtie_salmon_k_mer_31/results/bowtie"

  # rule params
  adapter: "TGGAATTCTCGGGTGCCAAGG"
  filter_RNAs: "\"rRNA rRNA_pseudogene tRNA tRNA_pseudogene\""
  filter_chromosomes: "MtDNA"

  # samples
  experiment_samples: {
    WT: ["wild_type_33_Hrs_Rev1_REPLICATE_A", "wild_type_38_Hrs_Rev5_REPLICATE_A", "wild_type_33_Hrs_Rev1_REPLICATE_B", "wild_type_38_Hrs_Rev5_REPLICATE_B"],
    dpf_3_delta: ["dpf_3_delta_33_Hrs_Rev2_REPLICATE_A", "dpf_3_delta_38_Hrs_Rev6_REPLICATE_A", "dpf_3_delta_33_Hrs_Rev2_REPLICATE_B", "dpf_3_delta_38_Hrs_Rev6_REPLICATE_B"],
    dpf_3S784A: ["dpf_3S784A_33_Hrs_Rev3_REPLICATE_A", "dpf_3S784A_38_Hrs_Rev7_REPLICATE_A", "dpf_3S784A_33_Hrs_Rev3_REPLICATE_B", "dpf_3S784A_38_Hrs_Rev7_REPLICATE_B"],
    drh_3_mutant: ["drh_3_mutant_33_Hrs_Rev4_REPLICATE_A", "drh_3_mutant_38_Hrs_Rev8_REPLICATE_A", "drh_3_mutant_33_Hrs_Rev4_REPLICATE_B", "drh_3_mutant_38_Hrs_Rev8_REPLICATE_B"],
    WT_33: ["wild_type_33_Hrs_Rev1_REPLICATE_A", "wild_type_33_Hrs_Rev1_REPLICATE_B"],
    WT_38: ["wild_type_38_Hrs_Rev5_REPLICATE_A", "wild_type_38_Hrs_Rev5_REPLICATE_B"],
    dpf_3_delta_33: ["dpf_3_delta_33_Hrs_Rev2_REPLICATE_A", "dpf_3_delta_33_Hrs_Rev2_REPLICATE_B"],
    dpf_3_delta_38: ["dpf_3_delta_38_Hrs_Rev6_REPLICATE_A", "dpf_3_delta_38_Hrs_Rev6_REPLICATE_B"],
    dpf_3S784A_33: ["dpf_3S784A_33_Hrs_Rev3_REPLICATE_A", "dpf_3S784A_33_Hrs_Rev3_REPLICATE_B"],
    dpf_3S784A_38: ["dpf_3S784A_38_Hrs_Rev7_REPLICATE_A", "dpf_3S784A_38_Hrs_Rev7_REPLICATE_B"],
    drh_3_mutant_33: ["drh_3_mutant_33_Hrs_Rev4_REPLICATE_A", "drh_3_mutant_33_Hrs_Rev4_REPLICATE_B"],
    drh_3_mutant_38: ["drh_3_mutant_38_Hrs_Rev8_REPLICATE_A", "drh_3_mutant_38_Hrs_Rev8_REPLICATE_B"]
  }

  # comparisons
  combinations: [["WT", "dpf_3_delta"],
                 ["WT", "dpf_3S784A"],
                 ["WT", "drh_3_mutant"],
                 ["WT_33", "dpf_3_delta_33"],
                 ["WT_38", "dpf_3_delta_38"],
                 ["WT_33", "dpf_3S784A_33"],
                 ["WT_38", "dpf_3S784A_38"],
                 ["WT_33", "drh_3_mutant_33"],
                 ["WT_38", "drh_3_mutant_38"]]
...
