---
  # general
  samples: "samples.tsv"
  output_dir: "results"
  logs: "logs"
  local_log: "logs/local_log"
  cluster_log: "logs/cluster_log"
  scripts: "../scripts"
  envs: "../envs/"

  # annotation
  gtf: "../00_annotation/results/annotation/canonical_geneset.exons.no_repeat_overlap_and_ce_11_repeats.filtered.merged.gtf"
  genome: "/tungstenfs/groups/gbioinfo/DB/WormBase/WS270/c_elegans.PRJNA13758.WS270.genomic.fa"
  gene_info: "/tungstenfs/groups/gbioinfo/DB/WormBase/WS270/c_elegans.PRJNA13758.WS270.geneIDs.txt"
  repeats_info: "../00_annotation/results/annotation/ce_11_repeats.filtered.tsv"
  bowtie_index: "../00_annotation/results/indexes/genome/bowtie"
  genome_size: "/tungstenfs/groups/gbioinfo/DB/WormBase/WS270/sizes.genome"

  # rule params
  transcript_biotype: "protein_coding,mRNA,repeat"
  kmer_len: ["5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]
  umi_length: 12
  adapter: "AACTGTAGGCACCATCAAT"
  filter_RNAs: "\"rRNA rRNA_pseudogene tRNA tRNA_pseudogene\""
  filter_chromosomes: "MtDNA"

  htseq_count__alignment_sorted_filtered_unique_mappers_mode: ["yes", "reverse"]

  # samples
  experiment_samples: {
    Input_WAGO-1: [Input_WAGO-1_A, Input_WAGO-1_B, Input_WAGO-1_C],
    Input_WAGO-1_dpf-3_null: [Input_WAGO-1_dpf-3_null_A, Input_WAGO-1_dpf-3_null_B, Input_WAGO-1_dpf-3_null_C],
    Input_WAGO-1_P3G: [Input_WAGO-1_P3G_A, Input_WAGO-1_P3G_B, Input_WAGO-1_P3G_C],
    Input_WAGO-3: [Input_WAGO-3_A, Input_WAGO-3_B, Input_WAGO-3_C],
    Input_WAGO-3_dpf-3_null: [Input_WAGO-3_dpf-3_null_A, Input_WAGO-3_dpf-3_null_B, Input_WAGO-3_dpf-3_null_C],
    Input_WAGO-4: [Input_WAGO-4_A, Input_WAGO-4_B, Input_WAGO-4_C],
    Input_WAGO-4_dpf-3_null: [Input_WAGO-4_dpf-3_null_A, Input_WAGO-4_dpf-3_null_B, Input_WAGO-4_dpf-3_null_C],
    IP_WAGO-1: [IP_WAGO-1_A, IP_WAGO-1_B, IP_WAGO-1_C],
    IP_WAGO-1_dpf-3_null: [IP_WAGO-1_dpf-3_null_A, IP_WAGO-1_dpf-3_null_B, IP_WAGO-1_dpf-3_null_C],
    IP_WAGO-1_P3G: [IP_WAGO-1_P3G_A, IP_WAGO-1_P3G_B, IP_WAGO-1_P3G_C],
    IP_WAGO-3: [IP_WAGO-3_A, IP_WAGO-3_B, IP_WAGO-3_C],
    IP_WAGO-3_dpf-3_null: [IP_WAGO-3_dpf-3_null_A, IP_WAGO-3_dpf-3_null_B, IP_WAGO-3_dpf-3_null_C],
    IP_WAGO-4: [IP_WAGO-4_A, IP_WAGO-4_B, IP_WAGO-4_C],
    IP_WAGO-4_dpf-3_null: [IP_WAGO-4_dpf-3_null_A, IP_WAGO-4_dpf-3_null_B, IP_WAGO-4_dpf-3_null_C],
  }

  # comparisons
  combinations: [[Input_WAGO-1, IP_WAGO-1],
                 [Input_WAGO-1_dpf-3_null, IP_WAGO-1_dpf-3_null],
                 [Input_WAGO-1_P3G, IP_WAGO-1_P3G],
                 [Input_WAGO-3, IP_WAGO-3],
                 [Input_WAGO-3_dpf-3_null, IP_WAGO-3_dpf-3_null],
                 [Input_WAGO-4, IP_WAGO-4],
                 [Input_WAGO-4_dpf-3_null, IP_WAGO-4_dpf-3_null],
                 [IP_WAGO-1_P3G, IP_WAGO-1],
                 [IP_WAGO-1_dpf-3_null, IP_WAGO-1],
                 [IP_WAGO-3_dpf-3_null, IP_WAGO-3],
                 [IP_WAGO-4_dpf-3_null, IP_WAGO-4]
                ]

  combinations_focus: [[IP_WAGO-1_P3G, IP_WAGO-1],
                       [IP_WAGO-1_dpf-3_null, IP_WAGO-1]]
...
